/// Flutter icons BottomNav
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNav
///      fonts:
///       - asset: fonts/BottomNav.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomNav {
  BottomNav._();

  static const String _kFontFam = 'BottomNav';

  static const IconData diary = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dumbbell = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData history = IconData(0xe802, fontFamily: _kFontFam);
}
